#!/usr/bin/env bash
# Download all openly-shared ERC proposals & reviews into the current folder tree
# Generated by Claude. Run from inside the ERC_Proposals_Online folder: bash download_all.sh
set +e

declare -a URLS FOLDERS NAMES PIS PARTS

URLS+=("https://gboleda.github.io/proposals/B1-AMORE-ERC_StG_2016-def.pdf"); FOLDERS+=("proposals/StG/Boleda_AMORE_StG_2016"); NAMES+=("B1-AMORE-ERC_StG_2016.pdf"); PIS+=("Gemma Boleda"); PARTS+=("B1")
URLS+=("https://gboleda.github.io/proposals/B2-AMORE-ERC_StG_2016-def.pdf"); FOLDERS+=("proposals/StG/Boleda_AMORE_StG_2016"); NAMES+=("B2-AMORE-ERC_StG_2016.pdf"); PIS+=("Gemma Boleda"); PARTS+=("B2")
URLS+=("https://zenodo.org/records/6860359/files/ERC_StG_2021_B1_FINAL.pdf?download=1"); FOLDERS+=("proposals/StG/Emery_CHILDCARE_STRATEGIES_StG_2021"); NAMES+=("ERC_StG_2021_B1_FINAL.pdf"); PIS+=("Thomas Emery"); PARTS+=("B1")
URLS+=("https://zenodo.org/records/6860359/files/ERC_StG_2021_B2_FINAL.pdf?download=1"); FOLDERS+=("proposals/StG/Emery_CHILDCARE_STRATEGIES_StG_2021"); NAMES+=("ERC_StG_2021_B2_FINAL.pdf"); PIS+=("Thomas Emery"); PARTS+=("B2")
URLS+=("https://zenodo.org/records/842734/files/list-2016-erc-proposal-shortened.pdf"); FOLDERS+=("proposals/StG/List_CALC_StG_2016"); NAMES+=("list-2016-erc-proposal-shortened.pdf"); PIS+=("Johann-Mattis List"); PARTS+=("B1+B2 (shortened)")
URLS+=("https://renebekkers.files.wordpress.com/2021/02/erc_bekkers_submitted.pdf"); FOLDERS+=("proposals/StG/Bekkers_Altruism_StG_2011"); NAMES+=("erc_bekkers_submitted.pdf"); PIS+=("Rene Bekkers"); PARTS+=("Full proposal")
URLS+=("http://weigelworld.org/fileadmin/weigelworld/About_Us/IMMUNEMESIS.pdf"); FOLDERS+=("proposals/AdG/Weigel_IMMUNEMESIS_AdG_2013"); NAMES+=("IMMUNEMESIS.pdf"); PIS+=("Detlef Weigel"); PARTS+=("Full proposal")
URLS+=("https://figshare.com/articles/journal_contribution/Strategic_Predictions_for_Quantum_Field_Theories/5142502"); FOLDERS+=("proposals/StG/Carrasco_StrategicPredictions_StG_2014"); NAMES+=("Carrasco_Strategic_Predictions_StG_2014.pdf"); PIS+=("John Joseph M. Carrasco"); PARTS+=("Full proposal (Figshare landing)")
URLS+=("https://figshare.com/articles/journal_contribution/My_successful_ERC_Starting_Grant_Proposal/7110767"); FOLDERS+=("proposals/StG/Anon_ERCStG_2010_successful"); NAMES+=("ERC_StG_2010_bundle.zip"); PIS+=("Anonymous (Figshare 7110767)"); PARTS+=("Bundle: B1, B2, budget, evaluation reports")
URLS+=("https://figshare.com/articles/online_resource/_Unsuccessful_ERC_StG_grant_application_evaluation/14256488"); FOLDERS+=("proposals/StG/Anon_ERCStG_2020_unsuccessful"); NAMES+=("Unsuccessful_ERC_StG_2020_bundle.zip"); PIS+=("Anonymous (Figshare 14256488)"); PARTS+=("B1 + B2 + evaluation report (redacted)")
URLS+=("https://drive.proton.me/urls/WTVN0F16HG#mYaz0edaOGha"); FOLDERS+=("proposals/CoG/vonHippel_Amplitudes_CoG_2023"); NAMES+=("vonHippel_ERC_CoG_2023.zip"); PIS+=("Matthew von Hippel"); PARTS+=("Zip (B1.pdf, B2.pdf, LaTeX source)")
URLS+=("https://figshare.com/articles/online_resource/ERC_Starting_Grant_proposal_Biotic_community_attributes_and_ecosystem_functioning_implications_for_predicting_and_mitigating_global_change_impacts_BIOCOM_/14633289"); FOLDERS+=("proposals/StG/Maestre_BIOCOM_StG_2009"); NAMES+=("BIOCOM_StG_2009.pdf"); PIS+=("Fernando T. Maestre"); PARTS+=("B1 + B2")
URLS+=("https://www.uv.es/gaita/pdf/ESR-PE5_647301.pdf"); FOLDERS+=("reviews/PE5_647301"); NAMES+=("ESR-PE5_647301.pdf"); PIS+=("(Anonymized ERC Consolidator applicant, panel PE5)"); PARTS+=("Step 2 Evaluation Report")

total=${#URLS[@]}; ok=0; fail=0; skipped=0
for i in "${!URLS[@]}"; do
  url="${URLS[$i]}"; folder="${FOLDERS[$i]}"; name="${NAMES[$i]}"; pi="${PIS[$i]}"
  mkdir -p "$folder"
  dest="$folder/$name"
  if [[ -s "$dest" ]]; then
    echo "SKIP $dest"
    skipped=$((skipped+1))
    continue
  fi
  printf "FETCH %-25s -> %s\n" "$pi" "$dest"
  if curl -sL --max-time 60 -A "Mozilla/5.0" -o "$dest" "$url"; then
    size=$(wc -c < "$dest")
    if (( size < 1000 )); then
      echo "  -> tiny file ($size bytes); may be a landing page; open in browser."
    fi
    ok=$((ok+1))
  else
    echo "  FAILED"
    fail=$((fail+1))
  fi
done
echo
echo "Done. $ok downloaded, $skipped skipped, $fail failed (of $total total)."
echo "Note: Figshare / Proton Drive items may need a one-click manual download from the landing page."