# Download all openly-shared ERC proposals & reviews into the current folder tree
# Generated by Claude. Run from inside the ERC_Proposals_Online folder.
$ErrorActionPreference = "Continue"
$ProgressPreference = "SilentlyContinue"

$items = @(
  @{ url = "https://gboleda.github.io/proposals/B1-AMORE-ERC_StG_2016-def.pdf"; folder = "proposals/StG/Boleda_AMORE_StG_2016"; filename = "B1-AMORE-ERC_StG_2016.pdf"; pi = "Gemma Boleda"; part = "B1" }
  @{ url = "https://gboleda.github.io/proposals/B2-AMORE-ERC_StG_2016-def.pdf"; folder = "proposals/StG/Boleda_AMORE_StG_2016"; filename = "B2-AMORE-ERC_StG_2016.pdf"; pi = "Gemma Boleda"; part = "B2" }
  @{ url = "https://zenodo.org/records/6860359/files/ERC_StG_2021_B1_FINAL.pdf?download=1"; folder = "proposals/StG/Emery_CHILDCARE_STRATEGIES_StG_2021"; filename = "ERC_StG_2021_B1_FINAL.pdf"; pi = "Thomas Emery"; part = "B1" }
  @{ url = "https://zenodo.org/records/6860359/files/ERC_StG_2021_B2_FINAL.pdf?download=1"; folder = "proposals/StG/Emery_CHILDCARE_STRATEGIES_StG_2021"; filename = "ERC_StG_2021_B2_FINAL.pdf"; pi = "Thomas Emery"; part = "B2" }
  @{ url = "https://zenodo.org/records/842734/files/list-2016-erc-proposal-shortened.pdf"; folder = "proposals/StG/List_CALC_StG_2016"; filename = "list-2016-erc-proposal-shortened.pdf"; pi = "Johann-Mattis List"; part = "B1+B2 (shortened)" }
  @{ url = "https://renebekkers.files.wordpress.com/2021/02/erc_bekkers_submitted.pdf"; folder = "proposals/StG/Bekkers_Altruism_StG_2011"; filename = "erc_bekkers_submitted.pdf"; pi = "Rene Bekkers"; part = "Full proposal" }
  @{ url = "http://weigelworld.org/fileadmin/weigelworld/About_Us/IMMUNEMESIS.pdf"; folder = "proposals/AdG/Weigel_IMMUNEMESIS_AdG_2013"; filename = "IMMUNEMESIS.pdf"; pi = "Detlef Weigel"; part = "Full proposal" }
  @{ url = "https://figshare.com/articles/journal_contribution/Strategic_Predictions_for_Quantum_Field_Theories/5142502"; folder = "proposals/StG/Carrasco_StrategicPredictions_StG_2014"; filename = "Carrasco_Strategic_Predictions_StG_2014.pdf"; pi = "John Joseph M. Carrasco"; part = "Full proposal (Figshare landing)" }
  @{ url = "https://figshare.com/articles/journal_contribution/My_successful_ERC_Starting_Grant_Proposal/7110767"; folder = "proposals/StG/Anon_ERCStG_2010_successful"; filename = "ERC_StG_2010_bundle.zip"; pi = "Anonymous (Figshare 7110767)"; part = "Bundle: B1, B2, budget, evaluation reports" }
  @{ url = "https://figshare.com/articles/online_resource/_Unsuccessful_ERC_StG_grant_application_evaluation/14256488"; folder = "proposals/StG/Anon_ERCStG_2020_unsuccessful"; filename = "Unsuccessful_ERC_StG_2020_bundle.zip"; pi = "Anonymous (Figshare 14256488)"; part = "B1 + B2 + evaluation report (redacted)" }
  @{ url = "https://drive.proton.me/urls/WTVN0F16HG#mYaz0edaOGha"; folder = "proposals/CoG/vonHippel_Amplitudes_CoG_2023"; filename = "vonHippel_ERC_CoG_2023.zip"; pi = "Matthew von Hippel"; part = "Zip (B1.pdf, B2.pdf, LaTeX source)" }
  @{ url = "https://figshare.com/articles/online_resource/ERC_Starting_Grant_proposal_Biotic_community_attributes_and_ecosystem_functioning_implications_for_predicting_and_mitigating_global_change_impacts_BIOCOM_/14633289"; folder = "proposals/StG/Maestre_BIOCOM_StG_2009"; filename = "BIOCOM_StG_2009.pdf"; pi = "Fernando T. Maestre"; part = "B1 + B2" }
  @{ url = "https://www.uv.es/gaita/pdf/ESR-PE5_647301.pdf"; folder = "reviews/PE5_647301"; filename = "ESR-PE5_647301.pdf"; pi = "(Anonymized ERC Consolidator applicant, panel PE5)"; part = "Step 2 Evaluation Report" }
)

$total = $items.Count
$ok = 0; $fail = 0; $skipped = 0
foreach ($it in $items) {
  $dest = Join-Path $it.folder $it.filename
  New-Item -ItemType Directory -Force -Path $it.folder | Out-Null
  if (Test-Path $dest -PathType Leaf) {
    Write-Host ("SKIP {0} (already on disk)" -f $dest)
    $skipped++; continue
  }
  Write-Host ("FETCH {0,-25} {1}" -f $it.pi, $dest)
  try {
    Invoke-WebRequest -Uri $it.url -OutFile $dest -UseBasicParsing -TimeoutSec 60 -ErrorAction Stop
    $size = (Get-Item $dest).Length
    if ($size -lt 1000) {
      Write-Warning ("  -> file is tiny ({0} bytes); the page may be a landing page rather than the PDF. Open the URL in a browser." -f $size)
    }
    $ok++
  } catch {
    Write-Warning ("  FAILED: " + $_.Exception.Message)
    $fail++
  }
}
Write-Host ""
Write-Host ("Done. {0} downloaded, {1} skipped, {2} failed (of {3} total)." -f $ok, $skipped, $fail, $total)
Write-Host "Note: Figshare / Proton Drive items may need a one-click manual download because they return a landing page rather than the binary."